scoreboard objectives add death_timer dummy 
scoreboard objectives add arg1 dummy
scoreboard objectives add arg2 dummy
scoreboard objectives add arg3 dummy
scoreboard objectives add killstreak dummy
scoreboard objectives add arrow dummy 残弾数
scoreboard objectives add arrow_trail dummy
scoreboard objectives add reload dummy
scoreboard objectives add reloadT dummy
scoreboard objectives add recast dummy
scoreboard objectives add recastT dummy
scoreboard objectives add job dummy
scoreboard objectives add park dummy
scoreboard objectives add acetime dummy
scoreboard objectives add ap dummy
scoreboard objectives add parkcountdown dummy
scoreboard objectives add countdown dummy
scoreboard objectives add gameending dummy
scoreboard objectives add ac1 dummy
scoreboard objectives add ac2 dummy
scoreboard objectives add ac3 dummy
scoreboard objectives add minigunrecast dummy
scoreboard objectives add skilllevel dummy
scoreboard objectives add e_marking dummy
scoreboard objectives add e_marking2 dummy
scoreboard objectives add UUID dummy
scoreboard objectives add weaponcooldown dummy
scoreboard objectives add sub_reload_ammo dummy
scoreboard objectives add count_stop dummy
scoreboard objectives add count_move dummy
scoreboard objectives add park_cooldown dummy