#矢の本数管理
replaceitem entity @a[tag=battle,scores={arrow=1}] slot.hotbar 8 arrow 1 0 {"minecraft:item_lock":{"mode":"lock_in_slot"}}
replaceitem entity @a[tag=battle,scores={arrow=2}] slot.hotbar 8 arrow 2 0 {"minecraft:item_lock":{"mode":"lock_in_slot"}}
replaceitem entity @a[tag=battle,scores={arrow=3}] slot.hotbar 8 arrow 3 0 {"minecraft:item_lock":{"mode":"lock_in_slot"}}
replaceitem entity @a[tag=battle,scores={arrow=4}] slot.hotbar 8 arrow 4 0 {"minecraft:item_lock":{"mode":"lock_in_slot"}}
replaceitem entity @a[tag=battle,scores={arrow=5}] slot.hotbar 8 arrow 5 0 {"minecraft:item_lock":{"mode":"lock_in_slot"}}
replaceitem entity @a[tag=battle,scores={arrow=6}] slot.hotbar 8 arrow 6 0 {"minecraft:item_lock":{"mode":"lock_in_slot"}}
replaceitem entity @a[tag=battle,scores={arrow=7}] slot.hotbar 8 arrow 7 0 {"minecraft:item_lock":{"mode":"lock_in_slot"}}
replaceitem entity @a[tag=battle,scores={arrow=8}] slot.hotbar 8 arrow 8 0 {"minecraft:item_lock":{"mode":"lock_in_slot"}}
replaceitem entity @a[tag=battle,scores={arrow=9}] slot.hotbar 8 arrow 9 0 {"minecraft:item_lock":{"mode":"lock_in_slot"}}
replaceitem entity @a[tag=battle,scores={arrow=10}] slot.hotbar 8 arrow 10 0 {"minecraft:item_lock":{"mode":"lock_in_slot"}}
replaceitem entity @a[tag=battle,scores={arrow=11}] slot.hotbar 8 arrow 11 0 {"minecraft:item_lock":{"mode":"lock_in_slot"}}
replaceitem entity @a[tag=battle,scores={arrow=12}] slot.hotbar 8 arrow 12 0 {"minecraft:item_lock":{"mode":"lock_in_slot"}}
replaceitem entity @a[tag=battle,scores={arrow=13}] slot.hotbar 8 arrow 13 0 {"minecraft:item_lock":{"mode":"lock_in_slot"}}
replaceitem entity @a[tag=battle,scores={arrow=14}] slot.hotbar 8 arrow 14 0 {"minecraft:item_lock":{"mode":"lock_in_slot"}}
replaceitem entity @a[tag=battle,scores={arrow=15}] slot.hotbar 8 arrow 15 0 {"minecraft:item_lock":{"mode":"lock_in_slot"}}
replaceitem entity @a[tag=battle,scores={arrow=16}] slot.hotbar 8 arrow 16 0 {"minecraft:item_lock":{"mode":"lock_in_slot"}}
replaceitem entity @a[tag=battle,scores={arrow=17}] slot.hotbar 8 arrow 17 0 {"minecraft:item_lock":{"mode":"lock_in_slot"}}
replaceitem entity @a[tag=battle,scores={arrow=18}] slot.hotbar 8 arrow 18 0 {"minecraft:item_lock":{"mode":"lock_in_slot"}}
replaceitem entity @a[tag=battle,scores={arrow=19}] slot.hotbar 8 arrow 19 0 {"minecraft:item_lock":{"mode":"lock_in_slot"}}
replaceitem entity @a[tag=battle,scores={arrow=20..}] slot.hotbar 8 arrow 20 0 {"minecraft:item_lock":{"mode":"lock_in_slot"}}
replaceitem entity @a[tag=battle,scores={arrow=..0}] slot.hotbar 8 barrier 1 0 {"minecraft:item_lock":{"mode":"lock_in_slot"}}